language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - psql -c 'CREATE DATABASE djangopeople;' -U postgres
  - PYTHONPATH=. django-admin.py test --settings=test_settings
